package com.eventlens.model;

public enum DropClassification {
    SEQUENCE_GAP,
    DUPLICATE_EVENT,
    OUT_OF_ORDER_EVENT,
    LATE_EVENT,
    CLIENT_DISPATCH_DROP,
    EVENTBRIDGE_TO_SQS_DROP,
    LAMBDA_THROTTLE_OR_SQS_BACKLOG,
    LAMBDA_CONSUMER_FAILURE,
    DLQ_RECOVERY_REQUIRED,
    NETWORK_OR_GATEWAY_DROP,
    SERVER_PROCESSING_DROP,
    ACK_DELIVERY_DROP,
    MISSING_BACKEND_RESPONSE,
    STALE_TURN_RESULT,
    MODERATOR_STATE_DRIFT,
    STALE_CLIENT_SCREEN,
    ROUND_DIALOG_OVERLAP,
    AUDIO_LEAK_AFTER_GAME_END,
    CHAT_ORDER_DRIFT,
    GUEST_PARTICIPATION_BYPASS,
    HEALTHY
}
